#!/bin/bash

# INSTALLER IPTV PANEL FOR ARMBIAN / DEBIAN / UBUNTU
# Handles existing Nginx installation by using a custom port.

# CONFIGURATION DEFAULTS
DB_NAME="iptv_panel"
DEFAULT_PORT="8080"
SITE_PATH="/var/www/html/iptv"

echo "=========================================="
echo "    🚀 IPTV PANEL ARMBIAN INSTALLER       "
echo "=========================================="

# 1. GATHER INPUTS
echo ""
echo "❓ CONFIGURATION:"
read -p "Enter MySQL Root Password (for setup): " DB_ROOT_PASS
read -p "Enter New Database User Password (app user): " DB_APP_PASS
read -p "Enter Port for IPTV Panel (Default: $DEFAULT_PORT): " PORT
PORT=${PORT:-$DEFAULT_PORT}

echo ""
echo "⚙️  Installing on Port: $PORT"
echo "⚙️  Database Name: $DB_NAME"
echo ""
echo "Press ENTER to continue or Ctrl+C to cancel..."
read

# 2. UPDATE & INSTALL DEPENDENCIES
echo "📦 UPDATING SYSTEM & INSTALLING PACKAGES..."
apt update
apt install -y nginx mariadb-server unzip git
apt install -y php-fpm php-mysql php-curl php-xml php-mbstring php-zip

# 3. DETECT PHP VERSION
PHP_VER=$(php -r "echo PHP_MAJOR_VERSION.'.'.PHP_MINOR_VERSION;")
echo "ℹ️  Detected PHP Version: $PHP_VER"

# 4. CONFIGURE DATABASE
echo "🛠️  CONFIGURING DATABASE..."
systemctl start mariadb
systemctl enable mariadb

# Create safe app user
APP_USER=${APP_USER:-"iptv_user"}

echo "👤 Creating Database User: $APP_USER"
mysql -u root -p"$DB_ROOT_PASS" -e "CREATE DATABASE IF NOT EXISTS $DB_NAME;"
mysql -u root -p"$DB_ROOT_PASS" -e "CREATE USER IF NOT EXISTS '$APP_USER'@'localhost' IDENTIFIED BY '$DB_APP_PASS';"
mysql -u root -p"$DB_ROOT_PASS" -e "GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$APP_USER'@'localhost';"
mysql -u root -p"$DB_ROOT_PASS" -e "FLUSH PRIVILEGES;"

echo "✅ Database ready."

# 5. SETUP FILES
echo "📂 SETTING UP FILES..."
mkdir -p $SITE_PATH

# Copy files from current directory (one level up if running from scripts/)
# We assume the user has uploaded the ENTIRE project folder to the server.
# If this script is in ./scripts/, we copy from ../ to $SITE_PATH
SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
PROJECT_ROOT=$(dirname "$SCRIPT_DIR")

echo "ℹ️  Source Directory: $PROJECT_ROOT"
cp -r "$PROJECT_ROOT/"* "$SITE_PATH/"
chown -R www-data:www-data $SITE_PATH
chmod -R 755 $SITE_PATH

# 6. UPDATE CONFIG.PHP
echo "📝 WRITING CONFIG..."
# Ensure includes dir exists
mkdir -p $SITE_PATH/includes

cat > $SITE_PATH/includes/config.php <<EOF
<?php
// FILE: includes/config.php
// Auto-generated by install_armbian.sh

\$db_host = 'localhost';
\$db_user = '$APP_USER';
\$db_pass = '$DB_APP_PASS';
\$db_name = '$DB_NAME';
EOF

# 7. CONFIGURE NGINX (CUSTOM PORT)
echo "🌐 CONFIGURING NGINX ON PORT $PORT..."
CONFIG_FILE="/etc/nginx/sites-available/iptv-$PORT"

cat > $CONFIG_FILE <<EOF
server {
    listen $PORT;
    server_name _;
    root $SITE_PATH;
    index index.php index.html;

    # Logs
    access_log /var/log/nginx/iptv_access.log;
    error_log /var/log/nginx/iptv_error.log;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php${PHP_VER}-fpm.sock;
    }

    location ~ /\.ht {
        deny all;
    }
}
EOF

# Enable Site
ln -sf $CONFIG_FILE /etc/nginx/sites-enabled/
# Start Nginx (Do not remove default site to preserve existing web)
nginx -t && systemctl restart nginx

# 8. OPEN FIREWALL (UFW)
if command -v ufw > /dev/null; then
    echo "🛡️  Allowing Port $PORT in UFW..."
    ufw allow $PORT/tcp
fi

echo "=================================================="
echo "🎉 INSTALLATION COMPLETE!"
echo "👉 Access your panel at: http://<YOUR-IP>:$PORT"
echo "👉 Database User: $APP_USER"
echo "👉 Database Pass: (Hidden)"
echo "=================================================="
